update dockerfile
Signed-off-by: Paul Schultz <pschultz@pobox.com>

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -72,12 +72,12 @@ RUN NODE_HEADERS_VERSION=$(node --version); echo "=== Install node headers $NODE
 RUN "$YARN" config set httpTimeout 600000
 
 RUN echo "=== YARN INSTALL ==="; FAILED=0; "$YARN" install --immutable; \
-  for d in /tmp/xfs-*; do if [[ -f ${d}/build.log ]]; then \
+  for d in $(find yarn-install.log); do \
   (( FAILED = FAILED + 1 )); \
   echo; echo $d; \
   echo "!!! YARN INSTALL FAILED !!!"; \
   cat ${d}/build.log; \
-  fi; done; \
+  done; \
   if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
 
 # Stage 3 - Build packages
@@ -100,29 +100,35 @@ RUN \
   cat packages/app/src/build-metadata.json; echo
 
 # suppress git warnings about dubious ownership in repository at '/opt/app-root/src' when building
-RUN echo "=== YARN BUILD (including dynamic plugins) ==="; FAILED=0; \
+RUN echo "=== YARN BUILD ==="; FAILED=0; \
   git config --global --add safe.directory /opt/app-root/src; \
   "$YARN" build || true; \
-  for d in $(find yarn-install.log); do \
+  for d in /tmp/xfs-*; do if [[ -f ${d}/build.log ]]; then \
   (( FAILED = FAILED + 1 )); echo; echo $d; echo "======"; cat ${d}; \
-  done; \
+  fi; done; \
   if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
 
 WORKDIR $CONTAINER_SOURCE/dynamic-plugins
 
-RUN echo "=== DYNAMIC PLUGIN YARN INSTALL ==="; FAILED=0; "$YARN" install --immutable || true; \
-  for d in /tmp/xfs-*; do if [[ -f ${d}/build.log ]]; then \
-  (( FAILED = FAILED + 1 )); echo; echo $d; echo "======"; cat ${d}/build.log; \
-  fi; done; \
+RUN echo "=== DYNAMIC PLUGIN YARN INSTALL ==="; FAILED=0; "$YARN" install --immutable; \
+  for d in $(find yarn-install.log); do \
+  (( FAILED = FAILED + 1 )); \
+  echo; echo $d; \
+  echo "!!! DYNAMIC PLUGIN YARN INSTALL FAILED !!!"; \
+  cat ${d}/build.log; \
+  done; \
   if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
 
-RUN echo "=== EXPORT DYNAMIC PLUGINS ==="; FAILED=0; "$YARN" export-dynamic || true; \
-  for d in /tmp/xfs-*; do if [[ -f ${d}/build.log ]]; then \
-  (( FAILED = FAILED + 1 )); echo; echo $d; echo "======"; cat ${d}/build.log; \
+RUN echo "=== EXPORT DYNAMIC PLUGINS ==="; FAILED=0; \
+  "$YARN" export-dynamic || true; \
+  for d in /tmp/xfs-*; do if [[ -f ${d}/export-dynamic.log ]]; then \
+  (( FAILED = FAILED + 1 )); echo; echo $d; echo "======"; cat ${d}; \
   fi; done; \
   if [[ $FAILED -gt 0 ]]; then exit $FAILED; fi
 
 RUN echo "=== YARN COPY DYNAMIC PLUGINS in $(pwd) ==="; "$YARN" copy-dynamic-plugins dist
+
+WORKDIR $CONTAINER_SOURCE
 
 # Stage 4 - Build the actual backend image and install production dependencies
 # Upstream only
